Repository OpenCannabis/RFC, pull requests merged in 2018-06, with the labels that each got.

#31 Feature: Lab Testing v2
  7/README.md
Labels: CLA: Ready, Spec: Extension, Status: Raw

#33 remove broken top links && use closing </a> tags
  10/README.md
  3/2-Datamodel.md
  3/3-Core-Structures.md
  3/4-Extension-Structures.md
  3/XB-Scalar-Value-Types.md
  4/README.md
  5/README.md
  6/README.md
  7/README.md
  8/README.md
  9/README.md
Labels: Cosmetic

#1 Raw: OpenCannabis (3/OCS)
  .clabot
  .github/CODEOWNERS
  .github/ISSUE_TEMPLATE.md
  .github/PULL_REQUEST_TEMPLATE.md
  .gitignore
  .travis.yml
  10/README.md
  3/1-Introduction.md
  3/2-Datamodel.md
  3/3-Core-Structures.md
  3/4-Extension-Structures.md
  3/COPYRIGHT.md
  3/LICENSE.md
  3/OpenCannabis-CCLA.pdf
  3/OpenCannabis-ICLA.pdf
  3/README.md
  3/XA-Message-Categories.md
  3/XB-Scalar-Value-Types.md
  3/XC-Datamodel-Map.md
  3/opencannabis.png
  3/raw.svg
  4/README.md
  5/README.md
  6/README.md
  7/README.md
  8/README.md
  9/README.md
  CODE_OF_CONDUCT.md
  CONTRIBUTING.md
  README.md
  RFC.iml
  RFC.ipr
  SUMMARY.md
  book.js
  logo.png
  package.json
  yarn.lock
Labels: CLA: Ready, Spec: Core, Status: Raw
