Repository OpenCannabis/RFC, pull requests merged in 2018-03, with the labels that each got.

#2 Models: Base
  3/3-Core-Structures.md
Labels: question, status:raw

#10 Hotfix: table of contents missing media
  3/3-Core-Structures.md
Labels: Bug, Cosmetic

#16 Project: CLA Bot
  .clabot
Labels: Enhancement

#12 Hotfix: structs inside base and fix nomnoml format
  3/3-Core-Structures.md
Labels: Bug, CLA: Ready

#14 Project: Code of Conduct
  CODE_OF_CONDUCT.md
Labels: CLA: Ready, Enhancement, Open for Comment
